# for linux compile, type make linux
# fixed by servusDei2018
all:
	gcc xboard.c CeeChess.c uci.c evaluate.c eval.h pvtable.c init.c bitboards.c hashkeys.c board.c data.c attack.c io.c movegen.c validate.c makemove.c perft.c search.c see.c misc.c -o CeeChess-v1.3.2.2.exe -O3 -s
linux:
	gcc xboard.c CeeChess.c uci.c evaluate.c eval.h pvtable.c init.c bitboards.c hashkeys.c board.c data.c attack.c io.c movegen.c validate.c makemove.c perft.c search.c see.c misc.c -o CeeChess-v1.3.2.2.exe -O3 -s -lm
